### ISSUE TITLE
Always on display prevents deep sleep

### ISSUE THREAD

**Issue by xiongzi** [Evolution-X-Devices/device_xiaomi_marble#6]
Always on display prevents deep sleep. After first flashing the devices enters deep sleep for 0% of the time.

As soon as I switch off the AOD, the smartphone goes into deep sleep.

**Comment by shaughzam** [comment]
Try to understand what A - O - D means first.

**ALWAYS.
ON.
DISPLAY.**

How can the device deep sleep with a display that's ALWAYS ON?
